-- This file is for use with Corona Game Edition
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:7020d565881db88216aa067894ab509e:cb335979e3dcfe5c45d7624b2c527e61:78b488c52efd15abdfbbebe2602fbb00$
--
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "Background/Background_0000",
				spriteColorRect = { x = 0, y = 0, width = 1100, height = 800 },
				textureRect = { x = 2, y = 2, width = 1100, height = 800 },
				spriteSourceSize = { width = 1100, height = 800 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Walls/Wall1_0000",
				spriteColorRect = { x = 478, y = 0, width = 154, height = 800 },
				textureRect = { x = 1104, y = 2, width = 154, height = 800 },
				spriteSourceSize = { width = 1100, height = 800 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Walls/Wall2_0000",
				spriteColorRect = { x = 518, y = 10, width = 70, height = 790 },
				textureRect = { x = 1260, y = 2, width = 70, height = 790 },
				spriteSourceSize = { width = 1100, height = 800 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "floor/Floor_0000",
				spriteColorRect = { x = 58, y = 346, width = 1004, height = 108 },
				textureRect = { x = 2, y = 804, width = 1004, height = 108 },
				spriteSourceSize = { width = 1100, height = 800 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "platform/Platform_0000",
				spriteColorRect = { x = 124, y = 368, width = 884, height = 52 },
				textureRect = { x = 2, y = 914, width = 884, height = 52 },
				spriteSourceSize = { width = 1100, height = 800 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

