-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:230a995de57e547dd9c06eff3f415737:2d784a2cdf84e1a72b638629e1dfc7e4:78b488c52efd15abdfbbebe2602fbb00$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "bckground/0000",
				spriteColorRect = { x = 0, y = 0, width = 1024, height = 800 },
				textureRect = { x = 2, y = 2, width = 1024, height = 800 },
				spriteSourceSize = { width = 1024, height = 800 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

