-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:a87a081cce77fe205b533a445bffbe63:ac9a91a525e0d2567dc12c791753fffd:8c471c90ed2f2eed613eeecf27e6bfdc$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "Arrow/Arrow_0000",
				spriteColorRect = { x = 272, y = 175, width = 18, height = 68 },
				textureRect = { x = 234, y = 164, width = 18, height = 68 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arrow/Impact_0000",
				spriteColorRect = { x = 266, y = 176, width = 28, height = 58 },
				textureRect = { x = 360, y = 366, width = 28, height = 58 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arrow/Impact_0001",
				spriteColorRect = { x = 271, y = 177, width = 30, height = 58 },
				textureRect = { x = 328, y = 366, width = 30, height = 58 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arrow/Impact_0002",
				spriteColorRect = { x = 268, y = 176, width = 24, height = 62 },
				textureRect = { x = 210, y = 372, width = 24, height = 62 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arrow/Impact_0003",
				spriteColorRect = { x = 273, y = 175, width = 18, height = 68 },
				textureRect = { x = 234, y = 94, width = 18, height = 68 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arrow/Impact_0004",
				spriteColorRect = { x = 272, y = 175, width = 18, height = 68 },
				textureRect = { x = 234, y = 164, width = 18, height = 68 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Bow/Bow_0000",
				spriteColorRect = { x = 213, y = 188, width = 146, height = 30 },
				textureRect = { x = 406, y = 66, width = 146, height = 30 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Bow/draw_0000",
				spriteColorRect = { x = 210, y = 188, width = 150, height = 40 },
				textureRect = { x = 254, y = 34, width = 150, height = 40 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Bow/draw_0001",
				spriteColorRect = { x = 213, y = 187, width = 148, height = 56 },
				textureRect = { x = 254, y = 76, width = 148, height = 56 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Bow/draw_0002",
				spriteColorRect = { x = 220, y = 186, width = 132, height = 62 },
				textureRect = { x = 254, y = 134, width = 132, height = 62 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Bow/release_0000",
				spriteColorRect = { x = 210, y = 184, width = 154, height = 58 },
				textureRect = { x = 98, y = 34, width = 154, height = 58 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Bow/release_0001",
				spriteColorRect = { x = 213, y = 188, width = 146, height = 30 },
				textureRect = { x = 406, y = 34, width = 146, height = 30 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0000",
				spriteColorRect = { x = 265, y = 186, width = 38, height = 48 },
				textureRect = { x = 510, y = 386, width = 38, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0001",
				spriteColorRect = { x = 265, y = 186, width = 38, height = 48 },
				textureRect = { x = 510, y = 386, width = 38, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0002",
				spriteColorRect = { x = 264, y = 189, width = 40, height = 46 },
				textureRect = { x = 408, y = 302, width = 40, height = 46 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0003",
				spriteColorRect = { x = 264, y = 189, width = 40, height = 46 },
				textureRect = { x = 408, y = 302, width = 40, height = 46 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0004",
				spriteColorRect = { x = 263, y = 183, width = 42, height = 52 },
				textureRect = { x = 420, y = 248, width = 42, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0005",
				spriteColorRect = { x = 263, y = 183, width = 42, height = 52 },
				textureRect = { x = 420, y = 248, width = 42, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0006",
				spriteColorRect = { x = 263, y = 181, width = 40, height = 54 },
				textureRect = { x = 366, y = 294, width = 40, height = 54 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0007",
				spriteColorRect = { x = 262, y = 186, width = 40, height = 48 },
				textureRect = { x = 468, y = 348, width = 40, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0008",
				spriteColorRect = { x = 263, y = 187, width = 38, height = 48 },
				textureRect = { x = 510, y = 336, width = 38, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0009",
				spriteColorRect = { x = 263, y = 187, width = 38, height = 48 },
				textureRect = { x = 510, y = 336, width = 38, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0010",
				spriteColorRect = { x = 266, y = 185, width = 36, height = 50 },
				textureRect = { x = 172, y = 384, width = 36, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0011",
				spriteColorRect = { x = 266, y = 185, width = 36, height = 50 },
				textureRect = { x = 172, y = 384, width = 36, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0012",
				spriteColorRect = { x = 265, y = 183, width = 38, height = 52 },
				textureRect = { x = 428, y = 350, width = 38, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0013",
				spriteColorRect = { x = 265, y = 183, width = 38, height = 52 },
				textureRect = { x = 428, y = 350, width = 38, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0014",
				spriteColorRect = { x = 263, y = 183, width = 42, height = 50 },
				textureRect = { x = 128, y = 384, width = 42, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Skid/Skid_0000",
				spriteColorRect = { x = 264, y = 178, width = 38, height = 56 },
				textureRect = { x = 306, y = 228, width = 38, height = 56 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Skid/Skid_0001",
				spriteColorRect = { x = 266, y = 180, width = 36, height = 54 },
				textureRect = { x = 390, y = 350, width = 36, height = 54 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Skid/Skid_0002",
				spriteColorRect = { x = 258, y = 190, width = 46, height = 44 },
				textureRect = { x = 482, y = 248, width = 46, height = 44 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Skid/Skid_0003",
				spriteColorRect = { x = 251, y = 202, width = 58, height = 32 },
				textureRect = { x = 32, y = 150, width = 58, height = 32 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Skid/Skid_0004",
				spriteColorRect = { x = 245, y = 208, width = 68, height = 28 },
				textureRect = { x = 254, y = 198, width = 68, height = 28 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Skid/Skid_0005",
				spriteColorRect = { x = 249, y = 205, width = 60, height = 30 },
				textureRect = { x = 32, y = 118, width = 60, height = 30 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Skid/Skid_0006",
				spriteColorRect = { x = 248, y = 204, width = 62, height = 32 },
				textureRect = { x = 32, y = 34, width = 62, height = 32 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bubblepop/Bubble_0000",
				spriteColorRect = { x = 248, y = 159, width = 72, height = 70 },
				textureRect = { x = 346, y = 198, width = 72, height = 70 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bubblepop/pop_0000",
				spriteColorRect = { x = 244, y = 153, width = 80, height = 84 },
				textureRect = { x = 196, y = 286, width = 80, height = 84 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bubblepop/pop_0001",
				spriteColorRect = { x = 237, y = 146, width = 92, height = 96 },
				textureRect = { x = 32, y = 286, width = 92, height = 96 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "cauldron/caudron_0000",
				spriteColorRect = { x = 237, y = 172, width = 94, height = 64 },
				textureRect = { x = 194, y = 436, width = 94, height = 64 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "cauldron/caudron_0001",
				spriteColorRect = { x = 237, y = 172, width = 94, height = 64 },
				textureRect = { x = 98, y = 436, width = 94, height = 64 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "cauldron/caudron_0002",
				spriteColorRect = { x = 237, y = 172, width = 94, height = 64 },
				textureRect = { x = 2, y = 436, width = 94, height = 64 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin/Coin_0000",
				spriteColorRect = { x = 263, y = 181, width = 40, height = 40 },
				textureRect = { x = 510, y = 294, width = 40, height = 40 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin/Coin_0001",
				spriteColorRect = { x = 266, y = 181, width = 32, height = 42 },
				textureRect = { x = 510, y = 436, width = 32, height = 42 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin/Coin_0002",
				spriteColorRect = { x = 270, y = 181, width = 26, height = 42 },
				textureRect = { x = 482, y = 444, width = 26, height = 42 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin/Coin_0003",
				spriteColorRect = { x = 275, y = 181, width = 18, height = 44 },
				textureRect = { x = 530, y = 248, width = 18, height = 44 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin/Coin_0004",
				spriteColorRect = { x = 270, y = 180, width = 26, height = 44 },
				textureRect = { x = 482, y = 398, width = 26, height = 44 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin/Coin_0005",
				spriteColorRect = { x = 267, y = 180, width = 32, height = 44 },
				textureRect = { x = 450, y = 302, width = 32, height = 44 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "platform/Platform_0000",
				spriteColorRect = { x = 0, y = 193, width = 550, height = 30 },
				textureRect = { x = 2, y = 2, width = 550, height = 30 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0000",
				spriteColorRect = { x = 257, y = 172, width = 52, height = 44 },
				textureRect = { x = 32, y = 184, width = 52, height = 44 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0001",
				spriteColorRect = { x = 262, y = 162, width = 46, height = 54 },
				textureRect = { x = 420, y = 192, width = 46, height = 54 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0002",
				spriteColorRect = { x = 255, y = 156, width = 60, height = 48 },
				textureRect = { x = 32, y = 68, width = 60, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0003",
				spriteColorRect = { x = 241, y = 147, width = 96, height = 72 },
				textureRect = { x = 384, y = 426, width = 96, height = 72 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0004",
				spriteColorRect = { x = 220, y = 124, width = 134, height = 92 },
				textureRect = { x = 98, y = 94, width = 134, height = 92 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0005",
				spriteColorRect = { x = 221, y = 108, width = 136, height = 92 },
				textureRect = { x = 404, y = 98, width = 136, height = 92 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0006",
				spriteColorRect = { x = 233, y = 106, width = 116, height = 96 },
				textureRect = { x = 98, y = 188, width = 116, height = 96 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0007",
				spriteColorRect = { x = 258, y = 106, width = 68, height = 96 },
				textureRect = { x = 126, y = 286, width = 68, height = 96 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0008",
				spriteColorRect = { x = 287, y = 106, width = 38, height = 56 },
				textureRect = { x = 266, y = 228, width = 38, height = 56 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0009",
				spriteColorRect = { x = 299, y = 106, width = 24, height = 44 },
				textureRect = { x = 484, y = 294, width = 24, height = 44 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Puff_0000",
				spriteColorRect = { x = 261, y = 176, width = 48, height = 48 },
				textureRect = { x = 216, y = 234, width = 48, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Puff_0001",
				spriteColorRect = { x = 260, y = 170, width = 48, height = 54 },
				textureRect = { x = 32, y = 230, width = 48, height = 54 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Puff_0002",
				spriteColorRect = { x = 254, y = 160, width = 66, height = 54 },
				textureRect = { x = 482, y = 192, width = 66, height = 54 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Puff_0003",
				spriteColorRect = { x = 240, y = 138, width = 86, height = 78 },
				textureRect = { x = 278, y = 286, width = 86, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Puff_0004",
				spriteColorRect = { x = 235, y = 143, width = 92, height = 68 },
				textureRect = { x = 290, y = 432, width = 92, height = 68 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Puff_0005",
				spriteColorRect = { x = 230, y = 140, width = 90, height = 58 },
				textureRect = { x = 236, y = 372, width = 90, height = 58 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Puff_0006",
				spriteColorRect = { x = 234, y = 140, width = 94, height = 50 },
				textureRect = { x = 32, y = 384, width = 94, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "wall/Puff_0000",
				spriteColorRect = { x = 0, y = 0, width = 28, height = 400 },
				textureRect = { x = 2, y = 34, width = 28, height = 400 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

