-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:c066cb0b8a373635d6fc5256ac7c8b24:3575aa4c263f5194e8acd72479a0a659:8c471c90ed2f2eed613eeecf27e6bfdc$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "Arrow/Arrow_0000",
				spriteColorRect = { x = 274, y = 165, width = 18, height = 68 },
				textureRect = { x = 652, y = 2, width = 18, height = 68 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arrow/Impact_0000",
				spriteColorRect = { x = 268, y = 167, width = 28, height = 56 },
				textureRect = { x = 1160, y = 60, width = 28, height = 56 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arrow/Impact_0001",
				spriteColorRect = { x = 273, y = 165, width = 30, height = 60 },
				textureRect = { x = 970, y = 2, width = 30, height = 60 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arrow/Impact_0002",
				spriteColorRect = { x = 270, y = 166, width = 24, height = 64 },
				textureRect = { x = 808, y = 68, width = 24, height = 64 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arrow/Impact_0003",
				spriteColorRect = { x = 275, y = 164, width = 22, height = 70 },
				textureRect = { x = 574, y = 74, width = 22, height = 70 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arrow/Impact_0004",
				spriteColorRect = { x = 274, y = 165, width = 18, height = 68 },
				textureRect = { x = 632, y = 2, width = 18, height = 68 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Arrow/Impact_0005",
				spriteColorRect = { x = 274, y = 164, width = 18, height = 70 },
				textureRect = { x = 598, y = 74, width = 18, height = 70 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Bow.png",
				spriteColorRect = { x = 6, y = 0, width = 86, height = 31 },
				textureRect = { x = 698, y = 144, width = 86, height = 31 },
				spriteSourceSize = { width = 100, height = 141 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Bow/Bow_0000",
				spriteColorRect = { x = 213, y = 188, width = 146, height = 30 },
				textureRect = { x = 1796, y = 116, width = 146, height = 30 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Bow/draw_0000",
				spriteColorRect = { x = 210, y = 188, width = 150, height = 40 },
				textureRect = { x = 1450, y = 142, width = 150, height = 40 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Bow/draw_0001",
				spriteColorRect = { x = 213, y = 187, width = 148, height = 56 },
				textureRect = { x = 996, y = 126, width = 148, height = 56 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Bow/draw_0002",
				spriteColorRect = { x = 220, y = 186, width = 132, height = 62 },
				textureRect = { x = 834, y = 68, width = 132, height = 62 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Bow/release_0000",
				spriteColorRect = { x = 210, y = 184, width = 154, height = 58 },
				textureRect = { x = 1002, y = 2, width = 154, height = 58 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Bow/release_0001",
				spriteColorRect = { x = 213, y = 188, width = 146, height = 30 },
				textureRect = { x = 1796, y = 84, width = 146, height = 30 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death001.png",
				spriteColorRect = { x = 42, y = 24, width = 38, height = 50 },
				textureRect = { x = 1328, y = 2, width = 38, height = 50 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death002.png",
				spriteColorRect = { x = 35, y = 14, width = 40, height = 60 },
				textureRect = { x = 968, y = 64, width = 40, height = 60 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death003.png",
				spriteColorRect = { x = 30, y = 14, width = 52, height = 60 },
				textureRect = { x = 864, y = 2, width = 52, height = 60 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death004.png",
				spriteColorRect = { x = 25, y = 14, width = 50, height = 60 },
				textureRect = { x = 918, y = 2, width = 50, height = 60 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death005.png",
				spriteColorRect = { x = 19, y = 16, width = 56, height = 58 },
				textureRect = { x = 1102, y = 62, width = 56, height = 58 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death006.png",
				spriteColorRect = { x = 9, y = 26, width = 66, height = 48 },
				textureRect = { x = 786, y = 134, width = 66, height = 48 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death007.png",
				spriteColorRect = { x = 5, y = 32, width = 70, height = 42 },
				textureRect = { x = 1602, y = 140, width = 70, height = 42 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death008.png",
				spriteColorRect = { x = 23, y = 60, width = 52, height = 14 },
				textureRect = { x = 422, y = 168, width = 52, height = 14 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death009.png",
				spriteColorRect = { x = 23, y = 60, width = 52, height = 14 },
				textureRect = { x = 422, y = 168, width = 52, height = 14 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Idle/Idle_0000",
				spriteColorRect = { x = 263, y = 176, width = 38, height = 50 },
				textureRect = { x = 1322, y = 54, width = 38, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Idle/Idle_0001",
				spriteColorRect = { x = 260, y = 178, width = 44, height = 48 },
				textureRect = { x = 1526, y = 2, width = 44, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Idle/Idle_0002",
				spriteColorRect = { x = 257, y = 180, width = 48, height = 46 },
				textureRect = { x = 1840, y = 2, width = 48, height = 46 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Idle/Idle_0003",
				spriteColorRect = { x = 255, y = 180, width = 50, height = 44 },
				textureRect = { x = 1588, y = 94, width = 50, height = 44 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Idle/Idle_0004",
				spriteColorRect = { x = 258, y = 178, width = 46, height = 46 },
				textureRect = { x = 1890, y = 2, width = 46, height = 46 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Idle/Idle_0005",
				spriteColorRect = { x = 261, y = 178, width = 42, height = 48 },
				textureRect = { x = 1572, y = 2, width = 42, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Idle/Idle_0006",
				spriteColorRect = { x = 261, y = 177, width = 44, height = 48 },
				textureRect = { x = 1480, y = 2, width = 44, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Idle/Idle_0007",
				spriteColorRect = { x = 260, y = 176, width = 44, height = 50 },
				textureRect = { x = 950, y = 132, width = 44, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Idle/Idle_0008",
				spriteColorRect = { x = 259, y = 175, width = 42, height = 50 },
				textureRect = { x = 1298, y = 112, width = 42, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0000",
				spriteColorRect = { x = 265, y = 186, width = 38, height = 48 },
				textureRect = { x = 1698, y = 2, width = 38, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0001",
				spriteColorRect = { x = 265, y = 186, width = 38, height = 48 },
				textureRect = { x = 1698, y = 2, width = 38, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0002",
				spriteColorRect = { x = 264, y = 189, width = 40, height = 46 },
				textureRect = { x = 1380, y = 106, width = 40, height = 46 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0003",
				spriteColorRect = { x = 264, y = 189, width = 40, height = 46 },
				textureRect = { x = 1380, y = 106, width = 40, height = 46 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0004",
				spriteColorRect = { x = 263, y = 183, width = 42, height = 52 },
				textureRect = { x = 1254, y = 114, width = 42, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0005",
				spriteColorRect = { x = 263, y = 183, width = 42, height = 52 },
				textureRect = { x = 1254, y = 114, width = 42, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0006",
				spriteColorRect = { x = 263, y = 181, width = 40, height = 54 },
				textureRect = { x = 1240, y = 58, width = 40, height = 54 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0007",
				spriteColorRect = { x = 262, y = 186, width = 40, height = 48 },
				textureRect = { x = 1616, y = 2, width = 40, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0008",
				spriteColorRect = { x = 263, y = 187, width = 38, height = 48 },
				textureRect = { x = 1658, y = 2, width = 38, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0009",
				spriteColorRect = { x = 263, y = 187, width = 38, height = 48 },
				textureRect = { x = 1658, y = 2, width = 38, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0010",
				spriteColorRect = { x = 266, y = 185, width = 36, height = 50 },
				textureRect = { x = 1342, y = 106, width = 36, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0011",
				spriteColorRect = { x = 266, y = 185, width = 36, height = 50 },
				textureRect = { x = 1342, y = 106, width = 36, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0012",
				spriteColorRect = { x = 265, y = 183, width = 38, height = 52 },
				textureRect = { x = 1282, y = 58, width = 38, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0013",
				spriteColorRect = { x = 265, y = 183, width = 38, height = 52 },
				textureRect = { x = 1282, y = 58, width = 38, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Run/Run_0014",
				spriteColorRect = { x = 263, y = 183, width = 42, height = 50 },
				textureRect = { x = 1284, y = 2, width = 42, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Skid/Skid_0000",
				spriteColorRect = { x = 264, y = 178, width = 38, height = 56 },
				textureRect = { x = 1146, y = 122, width = 38, height = 56 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Skid/Skid_0001",
				spriteColorRect = { x = 266, y = 180, width = 36, height = 54 },
				textureRect = { x = 1246, y = 2, width = 36, height = 54 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Skid/Skid_0002",
				spriteColorRect = { x = 258, y = 190, width = 46, height = 44 },
				textureRect = { x = 1640, y = 94, width = 46, height = 44 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Skid/Skid_0003",
				spriteColorRect = { x = 251, y = 202, width = 58, height = 32 },
				textureRect = { x = 638, y = 144, width = 58, height = 32 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Skid/Skid_0004",
				spriteColorRect = { x = 245, y = 208, width = 68, height = 28 },
				textureRect = { x = 1380, y = 154, width = 68, height = 28 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Skid/Skid_0005",
				spriteColorRect = { x = 249, y = 205, width = 60, height = 30 },
				textureRect = { x = 1778, y = 148, width = 60, height = 30 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Skid/Skid_0006",
				spriteColorRect = { x = 248, y = 204, width = 62, height = 32 },
				textureRect = { x = 574, y = 146, width = 62, height = 32 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bubblepop/0000",
				spriteColorRect = { x = 247, y = 165, width = 72, height = 70 },
				textureRect = { x = 558, y = 2, width = 72, height = 70 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bubblepop/0001",
				spriteColorRect = { x = 246, y = 165, width = 74, height = 70 },
				textureRect = { x = 498, y = 96, width = 74, height = 70 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bubblepop/0002",
				spriteColorRect = { x = 245, y = 161, width = 76, height = 74 },
				textureRect = { x = 164, y = 100, width = 76, height = 74 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bubblepop/0003",
				spriteColorRect = { x = 247, y = 161, width = 72, height = 76 },
				textureRect = { x = 90, y = 100, width = 72, height = 76 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bubblepop/0004",
				spriteColorRect = { x = 246, y = 168, width = 74, height = 70 },
				textureRect = { x = 422, y = 96, width = 74, height = 70 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bubblepop/Pop_0000",
				spriteColorRect = { x = 243, y = 159, width = 80, height = 84 },
				textureRect = { x = 340, y = 96, width = 80, height = 84 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bubblepop/Pop_0001",
				spriteColorRect = { x = 236, y = 152, width = 92, height = 96 },
				textureRect = { x = 120, y = 2, width = 92, height = 96 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "cauldron/caudron_0000",
				spriteColorRect = { x = 237, y = 172, width = 94, height = 64 },
				textureRect = { x = 768, y = 2, width = 94, height = 64 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "cauldron/caudron_0001",
				spriteColorRect = { x = 237, y = 172, width = 94, height = 64 },
				textureRect = { x = 712, y = 68, width = 94, height = 64 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "cauldron/caudron_0002",
				spriteColorRect = { x = 237, y = 172, width = 94, height = 64 },
				textureRect = { x = 672, y = 2, width = 94, height = 64 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin/Coin_0000",
				spriteColorRect = { x = 263, y = 181, width = 40, height = 40 },
				textureRect = { x = 1736, y = 140, width = 40, height = 40 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin/Coin_0001",
				spriteColorRect = { x = 266, y = 181, width = 32, height = 42 },
				textureRect = { x = 1674, y = 140, width = 32, height = 42 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin/Coin_0002",
				spriteColorRect = { x = 270, y = 181, width = 26, height = 42 },
				textureRect = { x = 1708, y = 140, width = 26, height = 42 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin/Coin_0003",
				spriteColorRect = { x = 275, y = 181, width = 18, height = 44 },
				textureRect = { x = 1950, y = 48, width = 18, height = 44 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin/Coin_0004",
				spriteColorRect = { x = 270, y = 180, width = 26, height = 44 },
				textureRect = { x = 1768, y = 94, width = 26, height = 44 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin/Coin_0005",
				spriteColorRect = { x = 267, y = 180, width = 32, height = 44 },
				textureRect = { x = 1938, y = 2, width = 32, height = 44 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb001.png",
				spriteColorRect = { x = 31, y = 26, width = 28, height = 48 },
				textureRect = { x = 1810, y = 2, width = 28, height = 48 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb002.png",
				spriteColorRect = { x = 26, y = 26, width = 34, height = 48 },
				textureRect = { x = 1774, y = 2, width = 34, height = 48 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb003.png",
				spriteColorRect = { x = 27, y = 24, width = 34, height = 50 },
				textureRect = { x = 1362, y = 54, width = 34, height = 50 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb004.png",
				spriteColorRect = { x = 26, y = 28, width = 38, height = 44 },
				textureRect = { x = 1728, y = 94, width = 38, height = 44 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb005.png",
				spriteColorRect = { x = 26, y = 28, width = 36, height = 46 },
				textureRect = { x = 1460, y = 94, width = 36, height = 46 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb006.png",
				spriteColorRect = { x = 28, y = 27, width = 34, height = 48 },
				textureRect = { x = 1738, y = 2, width = 34, height = 48 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb007.png",
				spriteColorRect = { x = 28, y = 28, width = 34, height = 46 },
				textureRect = { x = 1498, y = 94, width = 34, height = 46 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb008.png",
				spriteColorRect = { x = 26, y = 28, width = 38, height = 44 },
				textureRect = { x = 1688, y = 94, width = 38, height = 44 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb009.png",
				spriteColorRect = { x = 27, y = 28, width = 36, height = 46 },
				textureRect = { x = 1422, y = 94, width = 36, height = 46 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "platform/Platform_0000",
				spriteColorRect = { x = 0, y = 193, width = 550, height = 30 },
				textureRect = { x = 1398, y = 52, width = 550, height = 30 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0000",
				spriteColorRect = { x = 257, y = 172, width = 52, height = 44 },
				textureRect = { x = 1534, y = 94, width = 52, height = 44 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0001",
				spriteColorRect = { x = 262, y = 162, width = 46, height = 54 },
				textureRect = { x = 1198, y = 2, width = 46, height = 54 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0002",
				spriteColorRect = { x = 255, y = 156, width = 60, height = 48 },
				textureRect = { x = 1368, y = 2, width = 60, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0003",
				spriteColorRect = { x = 241, y = 147, width = 96, height = 72 },
				textureRect = { x = 242, y = 100, width = 96, height = 72 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0004",
				spriteColorRect = { x = 220, y = 124, width = 134, height = 92 },
				textureRect = { x = 422, y = 2, width = 134, height = 92 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0005",
				spriteColorRect = { x = 221, y = 108, width = 136, height = 92 },
				textureRect = { x = 284, y = 2, width = 136, height = 92 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0006",
				spriteColorRect = { x = 233, y = 106, width = 116, height = 96 },
				textureRect = { x = 2, y = 2, width = 116, height = 96 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0007",
				spriteColorRect = { x = 258, y = 106, width = 68, height = 96 },
				textureRect = { x = 214, y = 2, width = 68, height = 96 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0008",
				spriteColorRect = { x = 287, y = 106, width = 38, height = 56 },
				textureRect = { x = 1158, y = 2, width = 38, height = 56 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Billow_0009",
				spriteColorRect = { x = 299, y = 106, width = 24, height = 44 },
				textureRect = { x = 1944, y = 94, width = 24, height = 44 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Puff_0000",
				spriteColorRect = { x = 261, y = 176, width = 48, height = 48 },
				textureRect = { x = 1430, y = 2, width = 48, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Puff_0001",
				spriteColorRect = { x = 260, y = 170, width = 48, height = 54 },
				textureRect = { x = 1190, y = 60, width = 48, height = 54 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Puff_0002",
				spriteColorRect = { x = 254, y = 160, width = 66, height = 54 },
				textureRect = { x = 1186, y = 118, width = 66, height = 54 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Puff_0003",
				spriteColorRect = { x = 240, y = 138, width = 86, height = 78 },
				textureRect = { x = 2, y = 100, width = 86, height = 78 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Puff_0004",
				spriteColorRect = { x = 235, y = 143, width = 92, height = 68 },
				textureRect = { x = 618, y = 74, width = 92, height = 68 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Puff_0005",
				spriteColorRect = { x = 230, y = 140, width = 90, height = 58 },
				textureRect = { x = 1010, y = 62, width = 90, height = 58 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smoke/Puff_0006",
				spriteColorRect = { x = 234, y = 140, width = 94, height = 50 },
				textureRect = { x = 854, y = 132, width = 94, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

