-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:05a06b8cf83854dbb2e5f3a8b04623c0:61eed6a1e6e1a6f9f1a3793e39e86d82:8c471c90ed2f2eed613eeecf27e6bfdc$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "Bow.png",
				spriteColorRect = { x = 6, y = 0, width = 86, height = 31 },
				textureRect = { x = 252, y = 64, width = 86, height = 31 },
				spriteSourceSize = { width = 100, height = 141 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death001.png",
				spriteColorRect = { x = 42, y = 24, width = 38, height = 50 },
				textureRect = { x = 836, y = 2, width = 38, height = 50 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death002.png",
				spriteColorRect = { x = 35, y = 14, width = 40, height = 60 },
				textureRect = { x = 358, y = 2, width = 40, height = 60 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death003.png",
				spriteColorRect = { x = 30, y = 14, width = 52, height = 60 },
				textureRect = { x = 252, y = 2, width = 52, height = 60 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death004.png",
				spriteColorRect = { x = 25, y = 14, width = 50, height = 60 },
				textureRect = { x = 306, y = 2, width = 50, height = 60 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death005.png",
				spriteColorRect = { x = 19, y = 16, width = 56, height = 58 },
				textureRect = { x = 400, y = 2, width = 56, height = 58 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death006.png",
				spriteColorRect = { x = 9, y = 26, width = 66, height = 48 },
				textureRect = { x = 722, y = 54, width = 66, height = 48 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death007.png",
				spriteColorRect = { x = 5, y = 32, width = 70, height = 42 },
				textureRect = { x = 538, y = 58, width = 70, height = 42 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death008.png",
				spriteColorRect = { x = 23, y = 60, width = 52, height = 14 },
				textureRect = { x = 96, y = 88, width = 52, height = 14 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death009.png",
				spriteColorRect = { x = 23, y = 60, width = 52, height = 14 },
				textureRect = { x = 96, y = 88, width = 52, height = 14 },
				spriteSourceSize = { width = 138, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/crouch_0000",
				spriteColorRect = { x = 264, y = 203, width = 46, height = 48 },
				textureRect = { x = 790, y = 54, width = 46, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/crouch_0001",
				spriteColorRect = { x = 267, y = 197, width = 42, height = 54 },
				textureRect = { x = 458, y = 2, width = 42, height = 54 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/run_0000",
				spriteColorRect = { x = 268, y = 199, width = 38, height = 50 },
				textureRect = { x = 796, y = 2, width = 38, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/run_0001",
				spriteColorRect = { x = 268, y = 199, width = 38, height = 50 },
				textureRect = { x = 796, y = 2, width = 38, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/run_0002",
				spriteColorRect = { x = 267, y = 201, width = 40, height = 48 },
				textureRect = { x = 838, y = 54, width = 40, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/run_0003",
				spriteColorRect = { x = 267, y = 201, width = 40, height = 48 },
				textureRect = { x = 838, y = 54, width = 40, height = 48 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/run_0004",
				spriteColorRect = { x = 266, y = 197, width = 42, height = 52 },
				textureRect = { x = 588, y = 2, width = 42, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/run_0005",
				spriteColorRect = { x = 266, y = 197, width = 42, height = 52 },
				textureRect = { x = 588, y = 2, width = 42, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/run_0006",
				spriteColorRect = { x = 266, y = 195, width = 40, height = 54 },
				textureRect = { x = 502, y = 2, width = 40, height = 54 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/run_0007",
				spriteColorRect = { x = 266, y = 199, width = 40, height = 50 },
				textureRect = { x = 754, y = 2, width = 40, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/run_0008",
				spriteColorRect = { x = 266, y = 199, width = 40, height = 50 },
				textureRect = { x = 712, y = 2, width = 40, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/run_0009",
				spriteColorRect = { x = 266, y = 199, width = 40, height = 50 },
				textureRect = { x = 712, y = 2, width = 40, height = 50 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/run_0010",
				spriteColorRect = { x = 268, y = 197, width = 38, height = 52 },
				textureRect = { x = 672, y = 2, width = 38, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/run_0011",
				spriteColorRect = { x = 268, y = 197, width = 38, height = 52 },
				textureRect = { x = 672, y = 2, width = 38, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/run_0012",
				spriteColorRect = { x = 268, y = 197, width = 38, height = 52 },
				textureRect = { x = 632, y = 2, width = 38, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/run_0013",
				spriteColorRect = { x = 268, y = 197, width = 38, height = 52 },
				textureRect = { x = 632, y = 2, width = 38, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Deud/run_0014",
				spriteColorRect = { x = 266, y = 197, width = 42, height = 52 },
				textureRect = { x = 544, y = 2, width = 42, height = 52 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bubblepop/Pop_0000",
				spriteColorRect = { x = 248, y = 157, width = 80, height = 84 },
				textureRect = { x = 96, y = 2, width = 80, height = 84 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bubblepop/Pop_0001",
				spriteColorRect = { x = 241, y = 150, width = 92, height = 96 },
				textureRect = { x = 2, y = 2, width = 92, height = 96 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bubblepop/bubble_0000",
				spriteColorRect = { x = 252, y = 163, width = 72, height = 70 },
				textureRect = { x = 178, y = 2, width = 72, height = 70 },
				spriteSourceSize = { width = 550, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb001.png",
				spriteColorRect = { x = 31, y = 26, width = 28, height = 48 },
				textureRect = { x = 916, y = 52, width = 28, height = 48 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb002.png",
				spriteColorRect = { x = 26, y = 26, width = 34, height = 48 },
				textureRect = { x = 912, y = 2, width = 34, height = 48 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb003.png",
				spriteColorRect = { x = 27, y = 24, width = 34, height = 50 },
				textureRect = { x = 876, y = 2, width = 34, height = 50 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb004.png",
				spriteColorRect = { x = 26, y = 28, width = 38, height = 44 },
				textureRect = { x = 498, y = 58, width = 38, height = 44 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb005.png",
				spriteColorRect = { x = 26, y = 28, width = 36, height = 46 },
				textureRect = { x = 648, y = 56, width = 36, height = 46 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb006.png",
				spriteColorRect = { x = 28, y = 27, width = 34, height = 48 },
				textureRect = { x = 880, y = 54, width = 34, height = 48 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb007.png",
				spriteColorRect = { x = 28, y = 28, width = 34, height = 46 },
				textureRect = { x = 686, y = 56, width = 34, height = 46 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb008.png",
				spriteColorRect = { x = 26, y = 28, width = 38, height = 44 },
				textureRect = { x = 458, y = 58, width = 38, height = 44 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fastZomb009.png",
				spriteColorRect = { x = 27, y = 28, width = 36, height = 46 },
				textureRect = { x = 610, y = 56, width = 36, height = 46 },
				spriteSourceSize = { width = 90, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

